[build]
  publish = "dist/gym/browser"
  command = "ng build"

# Configuración para PWA - Service Worker
[[headers]]
  for = "/ngsw-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/ngsw.json"
  [headers.values]
    Cache-Control = "no-cache"

# Configuración para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración para archivos JSON
[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

# Configuración para archivos de imagen
[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=31536000"

# REDIRECTS - Angular SPA routing
# Rutas específicas de tu aplicación
[[redirects]]
  from = "/inicio"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/usuario"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/conocenos"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/suscripcion"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ejercicio/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/equipo"
  to = "/index.html"
  status = 200

# Redirect para la ruta raíz que redirige a /inicio
[[redirects]]
  from = "/"
  to = "/inicio"
  status = 301

# Catch-all para cualquier otra ruta (debe ir al final)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración adicional para PWA
[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"